### ISSUE TITLE
[BUG] endless loading after reopening

### ISSUE THREAD

**Issue by AchimGrube** [ho-dev/HattrickOrganizer#1290]
**Describe the bug**
HO won't stop loading at step 'prepare to show' and takes up to 4 GB ram. It works again if i delete the database and copy a backup, but as soon as i close and reopen HO another time, the same bug appears.

**To Reproduce**
1. Delete db folder content
2. Copy db backup into db folder
3. Start HO
4. Close HO
5. Start HO again
6. See error

**Platform information:**
 - OS: Windows 10
 - Version: did use 3.xx, then uninstalled and installed 5.0.3836.2

**Additional context**
i've been using this installation for years and this behavior just appeared some days ago

**Comment by wsbrenk** [comment]
could you please provide your backup?

**Comment by AchimGrube** [comment]
[db_singleUser-2021-12-4.zip](https://github.com/akasolace/HO/files/7681710/db_singleUser-2021-12-4.zip)

**Comment by wsbrenk** [comment]
19:21:32 [Error]   core.HO: Launched from IDE otherwise there is a bug !
19:21:47 [Info]    core.db.DBUpdater: updateDBv300() successfully completed
19:21:48 [Error]   core.db.UserConfigurationTable: parameter spielerUebersichtsPanel_horizontalRightSplitPane is not stored in UserConfigurationTable
19:21:48 [Info]    core.model.HOVerwaltung: language used for interface is: Deutsch
19:21:48 [Error]   core.util.DateTimeUtils: ZoneID could not be identified from hashValue
19:21:48 [Error]   core.util.HTDatetimeBase: ZoneID could not be identified, reverting to System defaults !
19:21:49 [Info]    core.gui.HOMainFrame: This is HO! version 0.0 DEV (r0), have fun!
19:21:49 [Info]    core.gui.HOMainFrame: Operating system found: Windows 10 on amd64 (10.0)
19:21:49 [Info]    core.gui.HOMainFrame: Using java: 15.0.2 (AdoptOpenJDK)
19:23:32 [Error]   core.db.JDBCAdapter: JDBCAdapter.executeQuery : java.sql.SQLException: java.lang.OutOfMemoryError: Java heap space
Statement: SELECT * FROM MODULE_CONFIGURATION
java.sql.SQLException: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCStatement.executeQuery(Unknown Source)
	at core.db.JDBCAdapter.executeQuery(JDBCAdapter.java:58)
	at core.db.ModuleConfigTable.findAll(ModuleConfigTable.java:53)
	at core.db.DBManager.loadModuleConfigs(DBManager.java:2259)
	at core.module.config.ModuleConfig.load(ModuleConfig.java:168)
	at core.module.config.ModuleConfig.instance(ModuleConfig.java:25)
	at module.playeranalysis.PlayerAnalysisModule.initialize(PlayerAnalysisModule.java:23)
	at module.playeranalysis.PlayerAnalysisModule.<init>(PlayerAnalysisModule.java:19)
	at core.module.ModuleManager.initMap(ModuleManager.java:54)
	at core.module.ModuleManager.initialize(ModuleManager.java:68)
	at core.module.ModuleManager.<init>(ModuleManager.java:46)
	at core.module.ModuleManager.instance(ModuleManager.java:41)
	at core.gui.HOMainFrame.initComponents(HOMainFrame.java:426)
	at core.gui.HOMainFrame.<init>(HOMainFrame.java:151)
	at core.gui.HOMainFrame.instance(HOMainFrame.java:216)
	at core.HO.lambda$main$2(HO.java:209)
	at java.desktop/java.awt.event.InvocationEvent.dispatch$$$capture(InvocationEvent.java:316)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space

**Comment by wsbrenk** [comment]
looks like a bug in special events module:

![image](https://user-images.githubusercontent.com/11821502/145458741-6882c461-ce57-4b23-8215-05a367c112be.png)

**Comment by wsbrenk** [comment]
db update of the HO5 seems to cause the problem. debugger shows 38 entries in the config table before starting the update. at the end there are 32 and the table seems to be corrupted.

**Comment by wsbrenk** [comment]
Now I see that HO5 upgrade is probably not the reason. Even before the update, not 38 entries are loaded from the table, but only 32.

**Comment by wsbrenk** [comment]
now i found the number 38 in HO3 database.script file in index of config table. 
SET TABLE PUBLIC.MODULE_CONFIGURATION INDEX '1701063 0 38'

dumping the rows in the debugger only shows 32 rows.
i think the HO3 database files are corrupted.
