### ISSUE TITLE
[BUG] Cannot launch/startup HO version 6.1 

### ISSUE THREAD

**Issue by amss1976** [ho-dev/HattrickOrganizer#1838]
**Describe the bug**
For some months I have not been able to launch version 6.1 of HO.

**To Reproduce**
1. When it gets to "Initialize Database" it gives a Start Up error window
2. java.lang.NullPointerException: Cannot invoke "java.sql.ResultSet.close()" because "rs" is null
at core.db.UserConfigurationTable.getAllStringValues(UserConfigurationTable.java:105)
at core.db.UserConfigurationTable.load(UserConfigurationTable.java:180)
at core.db.DBManager.loadUserParameter(DBManager.java:1622)
at core.HO.main(HO.java:150)
at core.HOLauncher.main(HOLauncher.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

**Screenshots**

**Platform information:**
 - OS: Windows 10 Pro
 - Version 22H2, compilation 19045.2728

**Additional context**
Have updated version of JAVA installed.

**Comment by wsbrenk** [comment]
@amss1976 this part is refactored in new beta version of HO7. 

it is not unlikely that you are observing a consequential error of a corrupt database. Please check if you still have a backup from times when you could start HO and restore this.

HO database may get corrupted when your  computer shuts down without closing HO before.
