### ISSUE TITLE
[BUG] Error during startup

### ISSUE THREAD

**Issue by RanzEckenklauer** [ho-dev/HattrickOrganizer#1880]
**Describe the bug**
Every time I try to start two or more Ho-Databases (teams) at one time there is an error:
The startup responds with an error window...
"Starting error: An error has occurred during startup":
java.lang.UnsatisfiedLinkError: 'void com.github.weisj.darklaf.platform.windows.JNIDecorationsWindows.init()'
	at com.github.weisj.darklaf.platform.windows.JNIDecorationsWindows.init(Native Method)
	at com.github.weisj.darklaf.platform.windows.WindowsLibrary.afterLoad(WindowsLibrary.java:44)
	at com.github.weisj.darklaf.nativeutil.AbstractLibrary.updateLibrary(AbstractLibrary.java:49)
	at com.github.weisj.darklaf.platform.windows.WindowsDecorationsProvider.initialize(WindowsDecorationsProvider.java:54)
	at com.github.weisj.darklaf.platform.decorations.NativeDecorationsManager.initialize(NativeDecorationsManager.java:96)
	at com.github.weisj.darklaf.DarkLaf.setupDecorations(DarkLaf.java:146)
	at com.github.weisj.darklaf.DarkLaf.initialize(DarkLaf.java:138)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:592)
	at java.desktop/javax.swing.UIManager.setLookAndFeel(UIManager.java:639)
	at core.gui.theme.light.SolarizedLightTheme.loadTheme(SolarizedLightTheme.java:29)
	at core.gui.theme.ThemeManager.setCurrentTheme(ThemeManager.java:354)
	at core.HO.main(HO.java:164)
	at core.HOLauncher.main(HOLauncher.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

There never is any problem when I only start one Database, and the next when the first Startup completely finished.
best regards
Ranz Eckenklauer - Leo

**Comment by wsbrenk** [comment]
@RanzEckenklauer when i try to reproduce this error i changed my theme from Nimbus to Solarized Light and startet all of my 4 HO database instances in parallel without any problems or longer waiting times.
the task manager shows a workspace memory from 350 up to 430 MBytes for each HO process which seems to be no problem on my computer. Memory usage of  Nimbus theme (my favorite setting) is a little lower.
Before the team is selected (and the database is opened)  the memory usage is arount 60MBytes.

![image](https://github.com/akasolace/HO/assets/11821502/9a0a3435-7312-45e5-83e5-69e9c1f9877d)

**Comment by wsbrenk** [comment]
possible workaround: use of Nimbus skin instead of Solarized light

**Comment by wsbrenk** [comment]
@RanzEckenklauer In HO10 we updated to a new version of darklaf. Maybe this fix the error?!
