### ISSUE TITLE
java lang stackoverflowerror error

### ISSUE THREAD

**Issue by Alynn22** [ho-dev/HattrickOrganizer#1918]
Hello,

Every time I click File/Download, I get the following error:

java.lang.StackOverflowError
	at java.base/java.io.InputStream.<init>(InputStream.java:61)
	at java.base/java.io.FilterInputStream.<init>(FilterInputStream.java:60)
	at java.base/sun.net.www.MeteredStream.<init>(MeteredStream.java:50)
	at java.base/sun.net.www.http.KeepAliveStream.<init>(KeepAliveStream.java:60)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:1014)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:726)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308)
	at com.github.scribejava.core.httpclient.jdk.JDKHttpClient.doExecute(JDKHttpClient.java:139)
	at com.github.scribejava.core.httpclient.jdk.JDKHttpClient.execute(JDKHttpClient.java:94)
	at com.github.scribejava.core.oauth.OAuthService.execute(OAuthService.java:114)
	at core.net.MyConnector.getCHPPWebFile(MyConnector.java:630)
	at core.net.MyConnector.downloadPlayerDetails(MyConnector.java:432)
	at core.net.OnlineWorker.downloadPlayerDetails(OnlineWorker.java:1193)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:503)
	at core.model.player.Player.getMotherclubId(Player.java:492)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:505)
	at core.model.player.Player.getMotherclubId(Player.java:492)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:505)
	at core.model.player.Player.getMotherclubId(Player.java:492)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:505)
	at core.model.player.Player.getMotherclubId(Player.java:492)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:505)
	at core.model.player.Player.getMotherclubId(Player.java:492)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:505)
	at core.model.player.Player.getMotherclubId(Player.java:492)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:505)
........................................................................................................................................................................
	at core.model.player.Player.getMotherclubId(Player.java:492)
	at core.model.player.Player.downloadMotherclubInfoIfMissing(Player.java:505)

**Comment by wsbrenk** [comment]
#1914 duplicate
