### ISSUE TITLE
[BUG] Error downloading hrf file

### ISSUE THREAD

**Issue by Tauri41** [ho-dev/HattrickOrganizer#1919]
**Describe the bug**
When i select the Download option from the File menu, i get the error 
"Cannot invoke ObjectToString() because PreparedStatement is null
HO Version 7.2

**To Reproduce**
1. Go to 'File'
2. Click on 'Download.'
3. Initiate the download process

**Screenshots**
![image](https://github.com/ho-dev/HattrickOrganizer/assets/70149420/3d95d5b2-b3e1-4ebf-bdf3-cb504d319df3)

**Platform information:**
 - OS: Windows
 - Version:	Windows 10 Home
Versione	22H2
Build sistema operativo	19045.3448
Esperienza	Windows Feature Experience Pack 1000.19044.1000.0

**Additional context**

Error details

Java.lang.NullPointerException: Cannot invoke "Object.toString()" because "preparedStatement" is null
	at core.db.JDBCAdapter.executePreparedUpdate(JDBCAdapter.java:134)
	at core.db.AbstractTable.executePreparedInsert(AbstractTable.java:370)
	at core.db.AbstractTable.insert(AbstractTable.java:111)
	at core.db.AbstractTable.store(AbstractTable.java:99)
	at core.db.XtraDataTable.saveXtraDaten(XtraDataTable.java:42)
	at core.db.DBManager.saveXtraDaten(DBManager.java:1409)
	at core.model.HOModel.saveHRF(HOModel.java:578)
	at core.net.OnlineWorker.getHrf(OnlineWorker.java:106)
	at core.net.DownloadDialog.startDownload(DownloadDialog.java:305)
	at core.net.DownloadDialog.actionPerformed(DownloadDialog.java:87)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at com.github.weisj.darklaf.ui.button.DarkButtonListener.mouseReleased(DarkButtonListener.java:73)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by wsbrenk** [comment]
@Tauri41 I have no idea why the PreparedStatement is null here. 
If the error is reproducable, could you please upload die database backup zips. Then i could try to debug this.

**Comment by Tauri41** [comment]
Here's last zip DB
[db_user-2023-09-21.zip](https://github.com/ho-dev/HattrickOrganizer/files/12704241/db_user-2023-09-21.zip)

**Comment by wsbrenk** [comment]
this database is corrupted.

Please try to restore an older backup, which hopefully is not corrupted.

**Comment by Tauri41** [comment]
Restored an older backup and everything went just fine Thanks.
I don0t really know hoe the last database was corrupted. Iwas running HO 7.1, checked for upadtes, downloaded the 7.2, closed HO and started the update. After the update, i wasn't able to download anything.
Weird.

**Comment by wsbrenk** [comment]
@Tauri41 thanks for this information. I'm not sure too, when database corruption happens. Typically if the HO process is killed and not closed, i think.
