### ISSUE TITLE
[BUG] ArrayIndexOutOfBoundsException after new Install4J Linux install

### ISSUE THREAD

**Issue by tychobrailleur** [ho-dev/HattrickOrganizer#2002]
**Describe the bug**
After installing latest HO 8.0 dev release on Linux, the following error occurs:

```
java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at core.HO.main(HO.java:115)
	at core.HOLauncher.main(HOLauncher.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.install4j.runtime.launcher.UnixLauncher.start(UnixLauncher.java:71)
	at install4j.core.HOLauncher.main(Unknown Source)
```

**To Reproduce**
1. Take latest `HO-8.0-unix-DEV-JRE.sh` 
2. Run on Linux 
3. As installation completes, install4j tries to launch HO
4. Error is displayed

**Screenshots**

![Screenshot from 2023-12-22 09-22-29](https://github.com/ho-dev/HattrickOrganizer/assets/114285/6a06a981-dd65-422d-b338-c6be5098235a)

**Platform information:**
 - OS: Linux
 - Version N/A

**Additional context**
N/A

**Comment by tychobrailleur** [comment]
This seems to occur as `HO.main` tries to pull version from manifest.

**Comment by tychobrailleur** [comment]
The version in Manifest is only `major.minor` hence the issue:

```
Manifest-Version: 1.0
Implementation-Title: HO
Implementation-Version: 8.0
```

Probably a fallout from #1988
