### ISSUE TITLE
[BUG] Missing flags

### ISSUE THREAD

**Issue by wsbrenk** [ho-dev/HattrickOrganizer#2063]
Is it possible, that the flag collection in Beta 8 won't count the new flags?
...and the new countries (Guyana & Tahiti) are not included... at least flagwise....

**Comment by wsbrenk** [comment]
Neue Länder und Nationalmannschaften

Neben der Homegrown League begrüßen wir zur neuen Saison Guinea als neues Land. Wo wir gerade bei den neuen Ländern sind, es gibt einen Termin, zu dem alle Länder (auch die letzten neuen) im WM-System integriert werden. Das wird im Januar 2025 passieren. Der erste Wettbewerb, an dem alle Länder und ihre Nationalmannschaften teilnehmen können, ist die Kontinentalmeisterschaft, die im Januar beginnt.

**Comment by Michelinho96** [comment]
I have a player from Belize, it would be nice if he also had his nationality flag

**Comment by wsbrenk** [comment]
@Michelinho96 if i see it right, the belize flag is part of HO since version 4.

**Comment by Michelinho96** [comment]
https://ibb.co/rH304mP

Unfortunately it didn't work for me in any version

**Comment by wsbrenk** [comment]
@Michelinho96 please try the following workaround:

If not already done, activate the International friendly module in File->Settings->Modules (and restart HO)
In the International friendly module you'll find an update button that hopefully will download the missing country informations:

![image](https://github.com/ho-dev/HattrickOrganizer/assets/11821502/512a0825-3149-47c1-92a3-27544b7df503)

**Comment by Michelinho96** [comment]
Hi,

I try the workaround:
activate the International friendly module in File->Settings->Modules (and restart HO)
In the International friendly module the update shows error:
java.sql.SQLException: Parameter not set
      at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
      at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
      at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
      at org.hsqldb.jdbc.JDBCPreparedStatement.checkParametersSet(Unknown Source)
      at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
      at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source)
      at core.db.ConnectionManager.executePreparedUpdate(ConnectionManager.kt:105)
      at core.db.ConnectionManager.executePreparedUpdate(ConnectionManager.kt:96)
      at core.db.AbstractTable.executePreparedDelete(AbstractTable.java:413)
      at core.db.IfaMatchTable.deleteAllMatches(IfaMatchTable.java:77)
      at core.db.DBManager.deleteIFAMatches(DBManager.java:2059)
      at module.ifa.menu.RebuildDialog.actionPerformed(RebuildDialog.java:94)
      at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
      at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
      at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
      at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
      at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
      at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
      at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
      at java.desktop/java.awt.Component.processEvent(Component.java:6391)
      at java.desktop/java.awt.Container.processEvent(Container.java:2266)
      at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
      at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
      at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
      at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
      at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
      at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
      at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
      at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
      at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
      at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
      at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
      at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
      at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
      at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
      at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
      at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
      at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
      at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
      at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
      at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
      at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
      at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
      at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
      at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.hsqldb.HsqlException: Parameter not set
      at org.hsqldb.error.Error.error(Unknown Source)
      at org.hsqldb.error.Error.error(Unknown Source)
      ... 45 more
________________________________
Von: wsbrenk ***@***.***>
Gesendet: Montag, 20. Mai 2024 17:31
An: ho-dev/HattrickOrganizer ***@***.***>
Cc: Michelinho96 ***@***.***>; Mention ***@***.***>
Betreff: Re: [ho-dev/HattrickOrganizer] [BUG] Missing flags (Issue #2063)


@Michelinho96<https://github.com/Michelinho96> please try the following workaround:

If not already done, activate the International friendly module in File->Settings->Modules (and restart HO)
In the International friendly module you'll find an update button that hopefully will download the missing country informations:

image.png (view on web)<https://github.com/ho-dev/HattrickOrganizer/assets/11821502/512a0825-3149-47c1-92a3-27544b7df503>

**Comment by Michelinho96** [comment]
Perfect, it works, thank you!

**Comment by wsbrenk** [comment]
mail from @Michelinho96 :

Hi, 

I try the workaround: 
activate the International friendly module in File->Settings->Modules (and restart HO) 
In the International friendly module the update shows error: 
java.sql.SQLException: Parameter not set 
      at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) 
      at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) 
      at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) 
      at org.hsqldb.jdbc.JDBCPreparedStatement.checkParametersSet(Unknown Source) 
      at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) 
      at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source) 
      at core.db.ConnectionManager.executePreparedUpdate(ConnectionManager.kt:105) 
      at core.db.ConnectionManager.executePreparedUpdate(ConnectionManager.kt:96) 
      at core.db.AbstractTable.executePreparedDelete(AbstractTable.java:413) 
      at core.db.IfaMatchTable.deleteAllMatches(IfaMatchTable.java:77) 
      at core.db.DBManager.deleteIFAMatches(DBManager.java:2059) 
      at module.ifa.menu.RebuildDialog.actionPerformed(RebuildDialog.java:94) 
      at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972) 
      at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313) 
      at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405) 
      at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262) 
      at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279) 
      at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626) 
      at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389) 
      at java.desktop/java.awt.Component.processEvent(Component.java:6391) 
      at java.desktop/java.awt.Container.processEvent(Container.java:2266) 
      at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001) 
      at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324) 
      at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833) 
      at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948) 
      at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575) 
      at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516) 
      at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310) 
      at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780) 
      at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833) 
      at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) 
      at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722) 
      at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716) 
      at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) 
      at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) 
      at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97) 
      at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746) 
      at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744) 
      at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) 
      at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) 
      at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743) 
      at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) 
      at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) 
      at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) 
      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) 
      at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
      at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) 
Caused by: org.hsqldb.HsqlException: Parameter not set 
      at org.hsqldb.error.Error.error(Unknown Source) 
      at org.hsqldb.error.Error.error(Unknown Source) 
      ... 45 more
