### ISSUE TITLE
[BUG] sql exception on ho startup

### ISSUE THREAD

**Issue by Spyluke** [ho-dev/HattrickOrganizer#2089]
**Describe the bug**
HO 8.0 start niet meer op Will not start
use windows 10
use java 8

this is the call 
java.sql.SQLException: IO error: RowInputBinary 4050469
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeQuery(Unknown Source)
	at core.db.ConnectionManager.executePreparedQuery(ConnectionManager.kt:73)
	at core.db.ConnectionManager.executePreparedQuery(ConnectionManager.kt:63)
	at core.db.AbstractTable.executePreparedSelect(AbstractTable.java:452)
	at core.db.AbstractTable.load(AbstractTable.java:189)
	at core.db.MatchLineupPlayerTable.getMatchLineupPlayers(MatchLineupPlayerTable.java:167)
	at core.db.DBManager.getMatchLineupPlayers(DBManager.java:674)
	at core.model.match.MatchLineupTeam.loadLineup(MatchLineupTeam.java:778)
	at core.db.DBManager.loadMatchLineupTeam(DBManager.java:2294)
	at core.db.DBManager.loadLineup(DBManager.java:2311)
	at core.db.DBManager.loadNextMatchLineup(DBManager.java:2306)
	at core.model.HOModel.<init>(HOModel.java:121)
	at core.model.HOVerwaltung.loadModel(HOVerwaltung.java:193)
	at core.model.HOVerwaltung.loadLatestHoModel(HOVerwaltung.java:117)
	at core.HO.main(HO.java:197)
	at core.HOLauncher.main(HOLauncher.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: org.hsqldb.HsqlException: IO error: RowInputBinary 4050469
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readInt(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.<init>(Unknown Source)
	at org.hsqldb.RowAVLDisk.<init>(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.findNode(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.getRight(Unknown Source)
	at org.hsqldb.index.IndexAVL.findNode(Unknown Source)
	at org.hsqldb.index.IndexAVL.findFirstRow(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.getFirstRow(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.initialiseIterator(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.next(Unknown Source)
	at org.hsqldb.QuerySpecification.buildResult(Unknown Source)
	at org.hsqldb.QuerySpecification.getResult(Unknown Source)
	at org.hsqldb.StatementQuery.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 24 more
Caused by: java.io.EOFException
	at org.hsqldb.lib.HsqlByteArrayInputStream.readInt(Unknown Source)
	... 44 more

How to solve the problem ?????

**Comment by wsbrenk** [comment]
java 8 is not a good idea, i think. Please try again with java 17. the easiest way would be using the installer including the correct java version: [HOSetup-8.0.631.2-DEV-JRE.exe](https://github.com/ho-dev/HattrickOrganizer/releases/download/8.0/HOSetup-8.0.631.2-DEV-JRE.exe)

**Comment by Spyluke** [comment]
It did not work i had installed the hosetup -8.0 that you send 

java.sql.SQLException: IO error: RowInputBinary 4050469
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeQuery(Unknown Source)
	at core.db.ConnectionManager.executePreparedQuery(ConnectionManager.kt:73)
	at core.db.ConnectionManager.executePreparedQuery(ConnectionManager.kt:63)
	at core.db.AbstractTable.executePreparedSelect(AbstractTable.java:452)
	at core.db.AbstractTable.load(AbstractTable.java:189)
	at core.db.MatchLineupPlayerTable.getMatchLineupPlayers(MatchLineupPlayerTable.java:167)
	at core.db.DBManager.getMatchLineupPlayers(DBManager.java:674)
	at core.model.match.MatchLineupTeam.loadLineup(MatchLineupTeam.java:778)
	at core.db.DBManager.loadMatchLineupTeam(DBManager.java:2294)
	at core.db.DBManager.loadLineup(DBManager.java:2311)
	at core.db.DBManager.loadNextMatchLineup(DBManager.java:2306)
	at core.model.HOModel.<init>(HOModel.java:121)
	at core.model.HOVerwaltung.loadModel(HOVerwaltung.java:193)
	at core.model.HOVerwaltung.loadLatestHoModel(HOVerwaltung.java:117)
	at core.HO.main(HO.java:197)
	at core.HOLauncher.main(HOLauncher.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: org.hsqldb.HsqlException: IO error: RowInputBinary 4050469
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.rowio.RowInputBinary.readInt(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.<init>(Unknown Source)
	at org.hsqldb.RowAVLDisk.<init>(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.persist.DataFileCache.getFromFile(Unknown Source)
	at org.hsqldb.persist.DataFileCache.get(Unknown Source)
	at org.hsqldb.persist.RowStoreAVLDisk.get(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.findNode(Unknown Source)
	at org.hsqldb.index.NodeAVLDisk.getRight(Unknown Source)
	at org.hsqldb.index.IndexAVL.findNode(Unknown Source)
	at org.hsqldb.index.IndexAVL.findFirstRow(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.getFirstRow(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.initialiseIterator(Unknown Source)
	at org.hsqldb.RangeVariable$RangeIteratorMain.next(Unknown Source)
	at org.hsqldb.QuerySpecification.buildResult(Unknown Source)
	at org.hsqldb.QuerySpecification.getResult(Unknown Source)
	at org.hsqldb.StatementQuery.getResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 24 more
Caused by: java.io.EOFException
	at org.hsqldb.lib.HsqlByteArrayInputStream.readInt(Unknown Source)
	... 44 more

Still got this tekst

Met vriendelijke groet,

Sheridan Akkerman
Werk
T 0880740424
M 0615367943
***@***.***
Privé
T 0320249103
M 06 25095354
***@***.***

Verzonden vanuit Mail voor Windows

Van: wsbrenk
Verzonden: maandag 24 juni 2024 20:24
Aan: ho-dev/HattrickOrganizer
CC: Spyluke; Author
Onderwerp: Re: [ho-dev/HattrickOrganizer] [BUG] (Issue #2089)

java 8 is not a good idea, i think. Please try again with java 17. the easiest way would be using the installer including the correct java version: HOSetup-8.0.631.2-DEV-JRE.exe

**Comment by wsbrenk** [comment]
have you tried to restore the database to the state before the first update (backup should be available in %APPDATA%/HO/db zip files).
For me it looks like a corrupted database file (maybe caused by your first update with an wrong java version or other reasons i. e. killing the update process!?)

**Comment by Spyluke** [comment]
That worked problem solved

Thanks

Verzonden vanuit Mail voor Windows

Van: wsbrenk
Verzonden: zaterdag 29 juni 2024 17:15
Aan: ho-dev/HattrickOrganizer
CC: Spyluke; Author
Onderwerp: Re: [ho-dev/HattrickOrganizer] [BUG] sql exception on ho startup(Issue #2089)

have you tried to restore the database to the state before the first update (backup should be available in %APPDATA%/HO/db zip files).
For me it looks like a corrupted database file (maybe caused by your first update with an wrong java version or other reasons i. e. killing the update process!?)
