### ISSUE TITLE
[BUG]Third team won't open

### ISSUE THREAD

**Issue by 007Mike1** [ho-dev/HattrickOrganizer#2205]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Platform information:**
 - OS: [Windows / macOS / Linux]
 - Version (including build number)

**Additional context**

**Comment by 007Mike1** [comment]
I got three teams in my HO database. With the first two I don't have any problems to open it.
But when I wan't to open my third team, I get next error.

java.sql.SQLException: General error
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.executeQuery(Unknown Source)
	at core.db.ConnectionManager.executePreparedQuery(ConnectionManager.kt:73)
	at core.db.ConnectionManager.executePreparedQuery(ConnectionManager.kt:63)
	at core.db.HRFTable.loadHRF(HRFTable.java:156)
	at core.db.HRFTable.loadHRF(HRFTable.java:142)
	at core.db.DBManager.loadHRF(DBManager.java:826)
	at core.model.HOModel.<init>(HOModel.java:107)
	at core.model.HOVerwaltung.loadModel(HOVerwaltung.java:193)
	at core.model.HOVerwaltung.loadLatestHoModel(HOVerwaltung.java:117)
	at core.HO.main(HO.java:197)
	at core.HOLauncher.main(HOLauncher.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
Caused by: org.hsqldb.HsqlException: General error
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.result.Result.newErrorResult(Unknown Source)
	at org.hsqldb.result.Result.newErrorResult(Unknown Source)
	at org.hsqldb.StatementDMQL.execute(Unknown Source)
	at org.hsqldb.Session.executeCompiledStatement(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 19 more

I don't had that problem past week, it worked perfect.  
Greetings,

**Comment by 007Mike1** [comment]
I work on windows

**Comment by wsbrenk** [comment]
This could be a corrupted database - this can happen if the ho application is killed during a database action.
Please try to restore a backup which is located in your database folder. On windows most propably in %APPDATA%/HO/dbn (with n=3 for your third team!??). There you'll find three zip files. Try to override your existing database files with the contents of one of your backups.

If that does not work, please load the backup zip to this thread, if you want us to debug this error.
