### ISSUE TITLE
[BUG] Open "league details" tab broken

### ISSUE THREAD

**Issue by jmbr4** [ho-dev/HattrickOrganizer#2214]
**Describe the bug**

When open a league details tab the program freeze and the memory consume increase up to  more than 6 gb

**To Reproduce**
1. Go to "league details" tab
2.  See error

**Screenshots**

**Platform information:**
 - OS: Windows
 - Version 9.0 DEV r. 725

**Comment by wsbrenk** [comment]
@jmbr4 this i cannot reproduce - could you please upload your latest database backup of your team to this thread. then i could try to debug that issue.

**Comment by jmbr4** [comment]
Of course!
[db_user-2024-12-29.zip](https://github.com/user-attachments/files/18271095/db_user-2024-12-29.zip)
This is a snapshot of task manager:
![image](https://github.com/user-attachments/assets/4e1ef04f-9298-440c-89b2-e3dc8b639977)

**Comment by jmbr4** [comment]
More info,

If I wait 15 min aprox, the cpu increase to 30% and memory to 8,5gb aprox, finally launch a java heap error:
![image](https://github.com/user-attachments/assets/271144a3-dc3a-4afe-bfe3-9a827d0a956e)

`java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3481)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:244)
	at java.base/java.util.ArrayList.add(ArrayList.java:454)
	at java.base/java.util.ArrayList.add(ArrayList.java:467)
	at module.series.MatchFixtures.FindReplacementOfTeam(MatchFixtures.java:327)
	at module.series.MatchFixtures.GetCurrentTeams(MatchFixtures.java:242)
	at module.series.MatchFixtures.calculateSeriesTable(MatchFixtures.java:220)
	at module.series.MatchFixtures.getTable(MatchFixtures.java:144)
	at module.series.SeriesTablePanel.populateSerieTable(SeriesTablePanel.java:237)
	at module.series.SeriesTablePanel.changeSaison(SeriesTablePanel.java:98)
	at module.series.SeriesPanel.informSaisonChange(SeriesPanel.java:124)
	at module.series.SeriesPanel.fillSaisonCB(SeriesPanel.java:120)
	at module.series.SeriesPanel.initialize(SeriesPanel.java:30)
	at core.gui.comp.panel.LazyImagePanel.callInitialize(LazyImagePanel.java:145)
	at core.gui.comp.panel.LazyImagePanel$2.hierarchyChanged(LazyImagePanel.java:132)
	at java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6793)
	at java.desktop/java.awt.Component.processEvent(Component.java:6412)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.Component.createHierarchyEvents(Component.java:5639)
	at java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1474)
	at java.desktop/java.awt.Component.show(Component.java:1691)
	at java.desktop/java.awt.Component.show(Component.java:1728)
	at java.desktop/java.awt.Component.setVisible(Component.java:1675)
	at java.desktop/javax.swing.JComponent.setVisible(JComponent.java:2720)
	at java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:422)
	at java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:295)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:148)
	at java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:79)
`
I promoted to VI division of VII, maibye the error is only in promotion cases.

In the log I can't see more relevant info, is the same of stactrace:

`2024-12-29 23:26:06 [Info]    core.HO: VERSION: 9.0   versionType:  DEV   RevisionNumber: 727
2024-12-29 23:26:07 [Info]    core.db.backup.HOZip: Create Backup: C:\Users\josem\AppData\Roaming\HO\db\db_user-2024-12-29.zip
2024-12-29 23:26:10 [Info]    core.db.DBManager: instance jdbc:hsqldb:file:C:\Users\josem\AppData\Roaming\HO\db/database; parent folder: C:\Users\josem\AppData\Roaming/HO
2024-12-29 23:26:11 [Info]    core.model.HOVerwaltung: language used for interface is: Spanish
2024-12-29 23:26:12 [Info]    core.training.TrainingWeekManager: Next week training date: 2025-01-03 01:00:00
2024-12-29 23:26:12 [Info]    core.gui.HOMainFrame: This is HO! version 9.0 DEV (r727), have fun!
2024-12-29 23:26:12 [Info]    core.gui.HOMainFrame: Operating system found: Windows 11 on amd64 (10.0)
2024-12-29 23:26:12 [Info]    core.gui.HOMainFrame: Using java: 17.0.3 (Eclipse Adoptium)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.lang.OutOfMemoryError: Java heap space
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.base/java.util.Arrays.copyOf(Arrays.java:3481)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.base/java.util.ArrayList.grow(ArrayList.java:237)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.base/java.util.ArrayList.grow(ArrayList.java:244)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.base/java.util.ArrayList.add(ArrayList.java:454)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.base/java.util.ArrayList.add(ArrayList.java:467)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: module.series.MatchFixtures.FindReplacementOfTeam(MatchFixtures.java:327)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: module.series.MatchFixtures.GetCurrentTeams(MatchFixtures.java:242)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: module.series.MatchFixtures.calculateSeriesTable(MatchFixtures.java:220)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: module.series.MatchFixtures.getTable(MatchFixtures.java:144)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: module.series.SeriesTablePanel.populateSerieTable(SeriesTablePanel.java:237)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: module.series.SeriesTablePanel.changeSaison(SeriesTablePanel.java:98)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: module.series.SeriesPanel.informSaisonChange(SeriesPanel.java:124)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: module.series.SeriesPanel.fillSaisonCB(SeriesPanel.java:120)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: module.series.SeriesPanel.initialize(SeriesPanel.java:30)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: core.gui.comp.panel.LazyImagePanel.callInitialize(LazyImagePanel.java:145)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: core.gui.comp.panel.LazyImagePanel$2.hierarchyChanged(LazyImagePanel.java:132)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.processHierarchyEvent(Component.java:6793)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.processEvent(Component.java:6412)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Container.processEvent(Container.java:2266)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.createHierarchyEvents(Component.java:5639)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Container.createHierarchyEvents(Container.java:1474)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.show(Component.java:1691)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.show(Component.java:1728)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/java.awt.Component.setVisible(Component.java:1675)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.JComponent.setVisible(JComponent.java:2720)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.JTabbedPane.fireStateChanged(JTabbedPane.java:422)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.JTabbedPane$ModelListener.stateChanged(JTabbedPane.java:295)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.DefaultSingleSelectionModel.fireStateChanged(DefaultSingleSelectionModel.java:148)
2024-12-29 23:46:44 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.DefaultSingleSelectionModel.setSelectedIndex(DefaultSingleSelectionModel.java:79)`

**Comment by tychobrailleur** [comment]
A quick look at this with visualvm, it seems that `MatchFixture#FindReplacementOfTeam` is the culprit, stuck on `findAny`.  I have the feeling that somehow the `replaces` list does not get emptied, going into an infinite loop.

**Comment by wsbrenk** [comment]
got it: 


![image](https://github.com/user-attachments/assets/db13bcb5-2fab-4020-a5e5-465a0e9faac6)

**Comment by wsbrenk** [comment]
@jmbr4 thanks - your backup helped a lot to find this error!
